"""Plot data generated by the compute_model.jl Julia script"""

import json
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import art3d, Axes3D

if __name__ == '__main__':
    for fname in ['outjson.json']:
        with open(fname, 'r') as f:
            ray = json.load(f)

        x = np.arange(0, 164, 4)
        xgrid, ygrid = np.meshgrid(x, x)
        z = np.array(ray)

        fig = plt.figure()
        ax = plt.axes(projection='3d')
        ax.plot_surface(xgrid, ygrid, z, rstride=1, cstride=1, cmap='viridis', edgecolor='none')
        ax.set_zlim(top=400, bottom=200)
    plt.show(block=True)